"""
BIND zone files: reading them in and writing them out.

A BIND zone file is the plain-text format DNS servers have used for decades,
and it is what you get when you export a domain from most registrars. It
looks like this:

    $ORIGIN example.com.
    $TTL 3600
    @        300  IN  A      192.0.2.1
    www      300  IN  CNAME  example.com.
    @        3600 IN  MX     10 mail.example.com.

The fiddly parts, all of which this parser handles:

  * "@" means the zone's own domain.
  * A name with no trailing dot is relative, so "www" means "www.example.com".
  * An empty name column means "same owner as the line above".
  * The TTL and the class ("IN") are both optional on any given line.
  * "(" and ")" let one record span several lines.
  * ";" starts a comment, unless it is inside a quoted string.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .dns_rules import RECORD_TYPES

# SOA is generated by the app, never imported from a file.
IMPORTABLE_TYPES = set(RECORD_TYPES) | {"SOA"}

# DNS classes. Only IN is used in practice, but the others are legal.
CLASSES = {"IN", "CH", "HS"}


@dataclass
class ParsedRecord:
    name: str
    type: str
    ttl: int
    value: str


@dataclass
class ParseResult:
    records: list[ParsedRecord] = field(default_factory=list)
    # Human-readable notes about lines we could not use, e.g.
    # "Line 12: record type SSHFP is not supported."
    warnings: list[str] = field(default_factory=list)


def _strip_comment(line: str) -> str:
    """Remove a trailing ';' comment, ignoring semicolons inside quotes."""
    out = []
    in_quotes = False
    for char in line:
        if char == '"':
            in_quotes = not in_quotes
        if char == ";" and not in_quotes:
            break
        out.append(char)
    return "".join(out)


def _join_parenthesised(lines: list[str]) -> list[tuple[int, str, bool]]:
    """
    Collapse records that span several lines with ( ) into one line each.

    Returns (line number, text, was_indented). The indent flag has to be
    captured here, before the text is normalised, because a line that starts
    with whitespace means "same owner name as the line above" -- and that
    information would otherwise be lost when we squash the whitespace.
    """
    joined: list[tuple[int, str, bool]] = []
    buffer = ""
    start_line = 0
    indented = False
    depth = 0

    for number, raw in enumerate(lines, start=1):
        text = _strip_comment(raw).rstrip()
        if not text.strip() and depth == 0:
            continue

        if depth == 0:
            start_line = number
            indented = text[:1].isspace()
            buffer = text
        else:
            buffer += " " + text.strip()

        depth += text.count("(") - text.count(")")

        if depth <= 0:
            cleaned = buffer.replace("(", " ").replace(")", " ")
            joined.append((start_line, " ".join(cleaned.split()), indented))
            buffer = ""
            depth = 0

    if buffer.strip():
        cleaned = buffer.replace("(", " ").replace(")", " ")
        joined.append((start_line, " ".join(cleaned.split()), indented))

    return joined


def _absolute(name: str, origin: str) -> str:
    """Turn a name from the file into a full domain name."""
    if name == "@":
        return origin
    if name.endswith("."):
        return name[:-1].lower()
    return f"{name}.{origin}".lower()


def parse_zone_file(text: str, zone_name: str, default_ttl: int = 300) -> ParseResult:
    """
    Read a zone file and return the records in it.

    zone_name is used as the origin when the file has no $ORIGIN line, and
    anything the parser cannot use becomes a warning rather than an error --
    importing 40 of 42 records is more useful than refusing the whole file.
    """
    result = ParseResult()
    origin = zone_name.lower().rstrip(".")
    ttl = default_ttl
    last_name: str | None = None

    for line_number, line, starts_indented in _join_parenthesised(text.splitlines()):
        if not line:
            continue

        # Directives
        if line.upper().startswith("$ORIGIN"):
            parts = line.split()
            if len(parts) > 1:
                origin = parts[1].rstrip(".").lower()
            continue
        if line.upper().startswith("$TTL"):
            parts = line.split()
            if len(parts) > 1 and parts[1].isdigit():
                ttl = int(parts[1])
            continue
        if line.startswith("$"):
            result.warnings.append(f"Line {line_number}: ignored directive {line.split()[0]}.")
            continue

        tokens = line.split()
        if not tokens:
            continue

        # An indented line, or one that opens with a TTL / class / type,
        # has no owner name of its own and reuses the previous one.
        first = tokens[0].upper()
        if starts_indented or first in IMPORTABLE_TYPES or first in CLASSES or tokens[0].isdigit():
            if last_name is None:
                result.warnings.append(
                    f"Line {line_number}: no record name, and no previous line to copy it from."
                )
                continue
            name = last_name
        else:
            name = _absolute(tokens[0], origin)
            tokens = tokens[1:]
            last_name = name

        # TTL and class may appear in either order, and both are optional.
        record_ttl = ttl
        while tokens:
            head = tokens[0].upper()
            if tokens[0].isdigit():
                record_ttl = int(tokens[0])
                tokens = tokens[1:]
            elif head in CLASSES:
                tokens = tokens[1:]
            else:
                break

        if not tokens:
            result.warnings.append(f"Line {line_number}: no record type found.")
            continue

        record_type = tokens[0].upper()
        value = " ".join(tokens[1:]).strip()

        if record_type == "SOA":
            # The app writes its own SOA, so the file's copy is ignored.
            continue
        if record_type not in RECORD_TYPES:
            result.warnings.append(
                f"Line {line_number}: record type {record_type} is not supported."
            )
            continue
        if not value:
            result.warnings.append(f"Line {line_number}: {record_type} record has no value.")
            continue

        # Targets in a zone file end with a dot; our storage does not use one.
        if record_type in ("CNAME", "NS", "PTR"):
            value = value.rstrip(".")
        elif record_type == "MX":
            bits = value.split()
            if len(bits) == 2:
                value = f"{bits[0]} {bits[1].rstrip('.')}"
        elif record_type == "SRV":
            bits = value.split()
            if len(bits) == 4:
                value = f"{bits[0]} {bits[1]} {bits[2]} {bits[3].rstrip('.')}"

        result.records.append(
            ParsedRecord(name=name, type=record_type, ttl=record_ttl, value=value)
        )

    return result


def export_zone_file(zone_name: str, name_servers: list[str], records: list) -> str:
    """Write the zone out as a BIND file, the reverse of parse_zone_file."""
    origin = zone_name.rstrip(".")
    lines = [
        f"; Zone file for {origin}",
        "; Exported from the Route 53 clone",
        f"$ORIGIN {origin}.",
        "$TTL 300",
        "",
    ]

    # Longest name decides the column width, so the file lines up neatly.
    width = max((len(r.name) for r in records), default=len(origin)) + 1

    for record in sorted(records, key=lambda r: (r.name != origin, r.name, r.type)):
        name = "@" if record.name == origin else f"{record.name}."
        for value in (record.value.splitlines() if record.value else [""]):
            target = value
            # Names on the right-hand side get their trailing dot back.
            if record.type in ("CNAME", "NS", "PTR") and not target.endswith("."):
                target = f"{target}."
            elif record.type == "MX":
                bits = target.split()
                if len(bits) == 2 and not bits[1].endswith("."):
                    target = f"{bits[0]} {bits[1]}."
            elif record.type == "SRV":
                bits = target.split()
                if len(bits) == 4 and not bits[3].endswith("."):
                    target = f"{bits[0]} {bits[1]} {bits[2]} {bits[3]}."
            lines.append(f"{name:<{width}} {record.ttl:<7} IN  {record.type:<6} {target}")

    return "\n".join(lines) + "\n"
